// Single source of truth for business facts. Keep these identical to the
// Google Business Profile (name, phone, service area) for local SEO.
export const config = {
  siteUrl: 'https://mydrtaxi.com',
  name: 'My DR Taxi',
  formerName: 'Winton Quick Services', // previous business name, for search/AI entity matching only
  driver: 'Winton',
  phone: '+18299295355',
  phoneDisplay: '+1 829-929-5355',
  whatsapp: '18299295355',
  googleMapsUrl: 'https://maps.app.goo.gl/aPBnN6ropype1h8V6',

  languages: ['en', 'es', 'fr', 'ru'],
  ogLocale: { en: 'en_US', es: 'es_DO', fr: 'fr_FR', ru: 'ru_RU' },

  // Site photography, relative to public/images/. `variants` are extra widths that
  // must exist as <name>-<width>.jpg next to the file (used for srcset).
  // A missing file renders the illustrated placeholder instead.
  // Generated by `npm run images` from assets/photos/*.png.
  photos: {
    hero: { file: 'winton-driving.jpg', width: 1672, height: 941, variants: [960] },
    avatar: { file: 'winton-avatar.jpg', width: 240, height: 240 },
    portrait: { file: 'meet-winton.jpg', width: 1536, height: 1024, variants: [800] },
    exterior: { file: 'vehicle/vehicle-exterior.jpg', width: 1448, height: 1086, variants: [800] },
    interior: { file: 'vehicle/vehicle-interior.jpg', width: 1448, height: 1086, variants: [800] },
    cta: { file: 'cta/cta-airport-arrival.jpg', width: 1672, height: 679, variants: [1100] },
  },

  // Airport card photography (2:3, no text). Code, name, area and the WhatsApp action
  // are live, translated HTML laid over the photo.
  airportCard: { width: 1024, height: 1536, variants: [600] },

  // Paste the embed code from your live Google Reviews widget provider
  // (e.g. Elfsight, Trustindex, EmbedSocial) between the backticks.
  // It is lazy-loaded only when visitors scroll near the reviews section.
  reviews: {
    embedHtml: ``,
  },

  // English names used in structured data.
  airports: [
    { code: 'POP', key: 'pop', name: 'Gregorio Luperón International Airport', city: 'Puerto Plata', card: 'airports/airport-pop.jpg' },
    { code: 'STI', key: 'sti', name: 'Cibao International Airport', city: 'Santiago de los Caballeros', card: 'airports/airport-sti.jpg' },
    { code: 'SDQ', key: 'sdq', name: 'Las Américas International Airport', city: 'Santo Domingo', card: 'airports/airport-sdq.jpg' },
    { code: 'PUJ', key: 'puj', name: 'Punta Cana International Airport', city: 'Punta Cana', card: 'airports/airport-puj.jpg' },
  ],

  // [from place key, to place key, approx. drive minutes]
  routes: [
    ['pop', 'sosua', 15],
    ['pop', 'cabarete', 30],
    ['pop', 'puertoPlata', 20],
    ['cabarete', 'sosua', 20],
    ['sti', 'cabarete', 105],
    ['sdq', 'cabarete', 240],
    ['puj', 'cabarete', 330],
  ],

  areaServed: [
    'Cabarete', 'Sosúa', 'Puerto Plata', 'Playa Dorada',
    'Santiago de los Caballeros', 'Santo Domingo', 'Punta Cana',
  ],
};
